ifndef S
S:=$(shell cd ../../../..; pwd)
endif
TARGET= ${S}/Targets/LS1C
SUBTARGET?=ls1c
CPPFLAGS=-mips2
START?=start_ls1c.o

%OBJS

%CFILES

%SFILES

%LOAD

export CFILES OBJS SFILES
include ${S}/Makefile.inc

%RULES
