# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Xilinx/CA_LAB/lab03/mycpu_verify/run_vivado/mycpu_prj1/mycpu.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/CA_LAB/lab03/mycpu_verify/run_vivado/mycpu_prj1/mycpu.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilinx/CA_LAB/lab03/mycpu_verify/run_vivado/mycpu_prj1/mycpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Xilinx/CA_LAB/lab03/soft/lab3_func_1/obj/inst_ram.coe
add_files D:/Xilinx/CA_LAB/lab03/soft/lab3_func_1/obj/data_ram.coe
read_verilog D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/head.h
set_property file_type "Verilog Header" [get_files D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/head.h]
read_verilog -library xil_defaultlib {
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/ALU.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/EXE_stage.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/ID_stage.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/IF_stage.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/MEM_stage.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/WB_stage.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/BRIDGE/bridge_1x2.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/CONFREG/confreg.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/divider_signed.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/divider_unsigned.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/multiplier_signed.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/multiplier_unsigned.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/mycpu.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/next_pc.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/regfile.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/myCPU/stall.v
  D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/soc_lite_top.v
}
read_ip -quiet D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc]
set_property is_locked true [get_files D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/data_ram/data_ram.xci]

read_ip -quiet D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc]
set_property is_locked true [get_files D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/inst_ram/inst_ram.xci]

read_ip -quiet D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property used_in_implementation false [get_files -all d:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/clk_pll/clk_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/clk_pll/clk_pll.xdc]
set_property used_in_implementation false [get_files -all d:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/clk_pll/clk_pll_ooc.xdc]
set_property is_locked true [get_files D:/Xilinx/CA_LAB/lab03/mycpu_verify/rtl/xilinx_ip/clk_pll/clk_pll.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx/CA_LAB/lab03/mycpu_verify/run_vivado/soc_lite.xdc
set_property used_in_implementation false [get_files D:/Xilinx/CA_LAB/lab03/mycpu_verify/run_vivado/soc_lite.xdc]


synth_design -top soc_lite_top -part xc7a200tfbg676-2


write_checkpoint -force -noxdef soc_lite_top.dcp

catch { report_utilization -file soc_lite_top_utilization_synth.rpt -pb soc_lite_top_utilization_synth.pb }
